export const projects = [
  {
    id: 1,
    name: "Project 1",
    likes: 10,
    image: "/images/projects/project-1.png",
    link: "/project-1",
    collaborators: ["polina-customer-support", "egor-3d-specialist"],
  },
  {
    id: 2,
    name: "Project 1",
    likes: 10,
    image: "/images/projects/project-1.png",
    link: "/project-1",
    collaborators: ["polina-customer-support", "egor-3d-specialist"],
  },
  {
    id: 3,
    name: "Project 1",
    likes: 10,
    image: "/images/projects/project-1.png",
    link: "/project-1",
    collaborators: ["polina-customer-support", "egor-3d-specialist"],
  },
  {
    id: 4,
    name: "Project 1",
    likes: 10,
    image: "/images/projects/project-1.png",
    link: "/project-1",
    collaborators: ["polina-customer-support", "egor-3d-specialist"],
  },
  {
    id: 5,
    name: "Project 1",
    likes: 10,
    image: "/images/projects/project-1.png",
    link: "/project-1",
    collaborators: ["polina-customer-support", "egor-3d-specialist"],
  },
  {
    id: 6,
    name: "Project 1",
    likes: 10,
    image: "/images/projects/project-1.png",
    link: "/project-1",
    collaborators: ["polina-customer-support", "egor-3d-specialist"],
  },
  {
    id: 7,
    name: "Project 1",
    likes: 10,
    image: "/images/projects/project-1.png",
    link: "/project-1",
    collaborators: ["polina-customer-support", "egor-3d-specialist"],
  },
];
