apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: community
nameSuffix: "-dev"
resources:
  - ../base
images:
  - name: harbor.arsolitt.tech/community42/portfolio
    newTag: v0.19
labels:
  - pairs:
      app.kubernetes.io/community-env: dev
    includeSelectors: true
patches:
  - target:
      kind: Ingress
      name: community-frontend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: community-dev.arsolitt.tech
      - op: replace
        path: /spec/tls/0/hosts/0
        value: community-dev.arsolitt.tech
      - op: replace
        path: /spec/tls/0/secretName
        value: wildcard.arsolitt.tech-tls
