name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run:
          curl -v https://harbor.arsolitt.tech
      - name: Checkout
        uses: actions/checkout@v4
      - name: Short SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 10
      - name: Login to App Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: ${{ vars.REGISTRY_HOST }}/${{ vars.REGISTRY_REPO }}/portfolio:latest
          tags: ${{ vars.REGISTRY_HOST }}/${{ vars.REGISTRY_REPO }}/portfolio:latest,${{ vars.REGISTRY_HOST }}/${{ vars.REGISTRY_REPO }}/portfolio:${{ steps.short-sha.outputs.sha }}
