name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v4
      - name: Short SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 10
      - name: Login to Docker Hub
        uses: https://github.com/docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up QEMU
        uses: https://github.com/docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Build and push
        uses: https://github.com/docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.REGISTRY_URL }}/portfolio:latest,${{ vars.REGISTRY_URL }}/portfolio:${{ steps.short-sha.outputs.sha }}
