name: Production

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    # container:
    #   image: harbor.arsolitt.ru/hub/goetzc/kaniko-ci:1.23.2
    # environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Short SHA
        id: short-sha
        uses: benjlevesque/short-sha@v3.0
        with:
          length: 7
      - uses: docker/login-action@v3.3.0
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: int128/kaniko-action@v1.35.0
        with:
          push: true
          tags: ${{ vars.REGISTRY_URL }}/community:${{ steps.short-sha.outputs.sha }}
          cache: true
          file: .docker/prod.dockerfile
          kaniko-args: --snapshot-mode=redo --cache-copy-layers=false #--snapshot-mode=redo --use-new-run --skip-tls-verify

      # - name: Build and push php
      #   uses: aevea/action-kaniko@master
      #   with:
      #     image: ${{ vars.REGISTRY_URL }}/community
      #     build_file: .docker/prod.dockerfile
      #     username: ${{ secrets.REGISTRY_USER }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}
      #     tag: ${{ steps.short-sha.outputs.sha }}
      #     tag_with_latest: true
      #     cache: true
      #     cache_registry: arsolitt/jexactyl-cache


      # - run: mkdir -p /kaniko/.docker
      # - run: echo "{\"auths\":{\"${{vars.REGISTRY_URL}}\":{\"auth\":\"$(printf "%s:%s" "${{secrets.REGISTRY_USER}}" "${{secrets.REGISTRY_PASSWORD}}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
      # # - run: cp ${ENV_FILE} ${CI_PROJECT_DIR}/.env

      # - run: >
      #     /kaniko/executor
      #     --context "${CI_PROJECT_DIR}"
      #     --dockerfile "${CI_PROJECT_DIR}/.docker/prod.dockerfile"
      #     --destination ${{ vars.REGISTRY_URL }}/community:${{ steps.short-sha.outputs.sha }}
      #     --cache=true
      #     --cache-copy-layers=false
      #     --snapshot-mode=redo
      #     --use-new-run
      #     --skip-tls-verify
